apiVersion: v1
kind: Secret
metadata:
  name: {{ include "immich.fullname" . }}-env
  labels:
    {{- include "immich.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "immich.secretEnv" . | nindent 2 }}

