apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "immich.fullname" . }}-server
  labels:
    {{- include "immich.serverLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  strategy:
    type: {{ .Values.server.deploymentStrategy }}
  selector:
    matchLabels:
      {{- include "immich.serverSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.server.configuration }}
        serverConfig/checksum: {{ include "immich.serverConfig" . | sha256sum }}
        {{- end }}
        secretEnv/checksum: {{ include "immich.server.secretEnv" . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "immich.serverLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          {{- if or .Values.server.configuration .Values.server.extraEnv }}
          env:
            {{- if .Values.server.configuration }}
            - name: IMMICH_CONFIG_FILE
              value: /config/immich-config.yaml
            {{- end }}
            {{- with .Values.server.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "immich.fullname" . }}-server-env
            {{- with .Values.server.extraEnvFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 2283
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          {{- with .Values.server.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.server.configuration .Values.server.volumes .Values.server.persistence.enabled }}
          volumeMounts:
            {{- if .Values.server.configuration }}
            - name: config
              mountPath: /config
            {{- end }}
            {{- if .Values.server.persistence.enabled }}
            - name: data
              mountPath: /data
            {{- end }}
            {{- with .Values.server.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      {{- if or .Values.server.configuration .Values.server.volumes .Values.server.persistence.enabled }}
      volumes:
        {{- if .Values.server.configuration }}
        - name: config
          configMap:
            name: {{ include "immich.fullname" . }}-server
        {{- end }}
        {{- if .Values.server.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "immich.server.persistence.claimName" . }}
        {{- end }}
        {{- with .Values.server.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
