{{- if and .Values.server.persistence.enabled (not .Values.server.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "immich.fullname" . }}-server
  labels:
    {{- include "immich.serverLabels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.server.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.size | quote }}
  {{- with .Values.server.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .Values.server.persistence.volumeName }}
  volumeName: {{ . }}
  {{- end }}
{{- end }}
