apiVersion: v2
name: immich
description: A chart to power Immich (immich.app) running on kubernetes
type: application
home: https://github.com/Javex/immich-helm
icon: https://raw.githubusercontent.com/immich-app/immich/main/design/immich-logo.svg
version: 0.2.4
appVersion: "v2.3.1"
maintainers:
  - name: Flozza
    email: code@inexplicity.de
    url: https://github.com/Javex/
dependencies:
  - name: valkey
    repository: https://valkey.io/valkey-helm/
    version: 0.8.1
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update README
      links:
        - name: GitHub PR
          url: https://github.com/Javex/immich-helm/pull/12
