apiVersion: v2
name: immich
description: A chart to power Immich (immich.app) running on kubernetes
type: application
home: https://github.com/Javex/immich-helm
icon: https://raw.githubusercontent.com/immich-app/immich/main/design/immich-logo.svg
version: 0.1.0
appVersion: "v2.3.1"
dependencies:
  - name: valkey
    repository: https://valkey.io/valkey-helm/
    version: 0.8.1
